CREATE TABLE Icons (
    IconId BIGINT PRIMARY KEY IDENTITY (1, 1),
    IconName NVARCHAR (255) NOT NULL,
    IconPath NVARCHAR (MAX) NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    UpdatedDate DATETIME NOT NULL DEFAULT GETDATE (),
    UpdatedBy NVARCHAR (128) NOT NULL
);